export const GET_APP_REVIEWS = "GET_APP_REVIEWS";
export const GET_APP_REVIEWS_SUCCESS = "GET_APP_REVIEWS_SUCCESS";
export const UPDATE_OPEN_DRAWER_VALUE = "UPDATE_OPEN_DRAWER_VALUE";
export const UPDATE_CHOSEN_REVIEW_ID = "UPDATE_CHOSEN_REVIEW_ID";
